import type { AppLocale } from "@/lib/locale";
import type { ProjectExecutionGroup } from "@/components/projects/project-detail-utils";
import { buildApiUrl, encodePathSegments } from "@/lib/api";
import type { ProjectFileEntry } from "@/types/api";

function appendCacheKey(path: string, cacheKey?: string | null) {
  const normalizedCacheKey = String(cacheKey || "").trim();
  if (!normalizedCacheKey) {
    return path;
  }

  const separator = path.includes("?") ? "&" : "?";
  return `${path}${separator}v=${encodeURIComponent(normalizedCacheKey)}`;
}

export function formatDate(value: string, locale: AppLocale = "es") {
  return new Intl.DateTimeFormat(locale === "es" ? "es-ES" : "en-US", {
    day: "numeric",
    month: "short",
    year: "numeric",
  }).format(new Date(value));
}

export function formatBytes(size: number) {
  if (size < 1024) {
    return `${size} B`;
  }

  if (size < 1024 * 1024) {
    return `${(size / 1024).toFixed(1)} KB`;
  }

  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
}

export function buildProjectFileUrl(
  owner: string,
  projectName: string,
  filePath: string,
  cacheKey?: string | null,
) {
  return appendCacheKey(
    buildApiUrl(
    `/api/projects/${encodeURIComponent(owner)}/download/${encodePathSegments(
      `${projectName}/${filePath}`,
    )}`,
    ),
    cacheKey,
  );
}

export function buildProjectFilePreviewPath(
  owner: string,
  projectName: string,
  filePath: string,
  cacheKey?: string | null,
) {
  return appendCacheKey(
    `/api/projects/${encodeURIComponent(owner)}/files/${encodePathSegments(
      `${projectName}/${filePath}`,
    )}`,
    cacheKey,
  );
}

export function isPreviewableTextFile(file: ProjectFileEntry) {
  return [".csv", ".htm", ".html", ".md", ".tsv", ".txt", ".yaml", ".yml"].includes(
    file.extension.toLowerCase(),
  );
}

export function canAttemptEmbeddedPreview(file: ProjectFileEntry) {
  return [".docx", ".xls", ".xlsx"].includes(file.extension.toLowerCase());
}

export function getArtifactLabel(extension: string, locale: AppLocale = "es") {
  const t = locale === "es";
  switch (extension.toLowerCase()) {
    case ".html":
    case ".htm":
      return t ? "Informe HTML" : "HTML report";
    case ".zip":
      return t ? "Paquete ZIP" : "ZIP package";
    case ".xlsx":
    case ".xls":
      return "Excel";
    case ".docx":
      return t ? "Documento" : "Document";
    default:
      return t ? "Artefacto" : "Artifact";
  }
}

export function getArtifactDescription(extension: string, locale: AppLocale = "es") {
  const t = locale === "es";
  switch (extension.toLowerCase()) {
    case ".html":
    case ".htm":
      return t
        ? "Abre el informe completo en una vista amplia dentro de la aplicación."
        : "Open full report in a wide in-app view.";
    case ".zip":
      return t
        ? "Descarga el paquete final con los resultados preparados para compartir o archivar."
        : "Download final package with results ready to share or archive.";
    case ".xlsx":
    case ".xls":
      return t
        ? "Consulta las tablas y resultados estructurados de esta ejecución."
        : "Review tables and structured results from this execution.";
    case ".docx":
      return t
        ? "Accede al documento generado para revisión o entrega."
        : "Access generated document for review or delivery.";
    default:
      return t
        ? "Abre el archivo principal generado por esta ejecución."
        : "Open main file generated by this execution.";
  }
}

export function getArtifactActionLabel(extension: string, locale: AppLocale = "es") {
  const t = locale === "es";
  switch (extension.toLowerCase()) {
    case ".html":
    case ".htm":
      return t ? "Abrir informe" : "Open report";
    case ".zip":
      return t ? "Descargar paquete" : "Download package";
    default:
      return t ? "Descargar archivo" : "Download file";
  }
}

export function getDeliverableTone(file: ProjectFileEntry) {
  switch (file.extension.toLowerCase()) {
    case ".zip":
      return "border-primary/20 bg-primary/5 text-primary";
    case ".html":
    case ".htm":
      return "border-emerald-200 bg-emerald-50 text-emerald-700";
    case ".xlsx":
    case ".xls":
      return "border-amber-200 bg-amber-50 text-amber-700";
    case ".docx":
      return "border-violet-200 bg-violet-50 text-violet-700";
    default:
      return "border-slate-200 bg-slate-50 text-slate-700";
  }
}

export function getDeliverablePriority(file: ProjectFileEntry) {
  switch (file.extension.toLowerCase()) {
    case ".html":
    case ".htm":
      return 0;
    case ".zip":
      return 1;
    case ".xlsx":
    case ".xls":
      return 2;
    case ".docx":
      return 3;
    default:
      return 4;
  }
}

export function getExecutionDeliverables(group: ProjectExecutionGroup) {
  return group.files.filter((file) =>
    [".docx", ".html", ".htm", ".xlsx", ".xls", ".zip"].includes(
      file.extension.toLowerCase(),
    ),
  );
}

export function getExecutionPreviewableFiles(group: ProjectExecutionGroup) {
  return getExecutionDeliverables(group).filter((file) => file.extension.toLowerCase() !== ".zip");
}

export function getProjectDeliverablesLayout(files: ProjectFileEntry[]) {
  const sortedDeliverables = [...files].sort((left, right) => {
    const priorityDifference = getDeliverablePriority(left) - getDeliverablePriority(right);
    if (priorityDifference !== 0) {
      return priorityDifference;
    }

    return left.name.localeCompare(right.name);
  });

  return {
    featuredDeliverable: sortedDeliverables[0] ?? null,
    secondaryDeliverables: sortedDeliverables.slice(1),
    sortedDeliverables,
  };
}
